version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
