services:
  app:
    container_name: nlp-backend-dev
    image: nlp-backend-dev
    build:
      target: development
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
